
name: Generate Snake

on:
  schedule:
    # Executa diariamente às 12:00 UTC
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v2.0.0
        with:
          github_user_name: SEU-NOME-DE-USUARIO
          outputs: dist/snake.svg
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
